name: WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli --version 0.2.79
      - name: Build wasm
        working-directory: ./bindings/js/wasm
        run: bash build-pkg.sh
      - working-directory: ./bindings/js/example
        run: yarn install
      - working-directory: ./bindings/js/example
        run: yarn test
